# This file contains the forks and their relevant upstreams to be synchronized with.
# Add the entries to this file appropriately, conforming to the YAML format.
---
oh-my-zsh:
  dir: ~/.oh-my-zsh
  upstream: robbyrussell/oh-my-zsh

vim-colorschemes:
  dir: ~/.vim/bundle/vim-colorschemes
  upstream: flazz/vim-colorschemes

vim-snippets:
  dir: ~/.vim/bundle/vim-snippets
  upstream: honza/vim-snippets
---
